language: go

go:
  - 1.10.x

env:
  matrix:
    - VERSION=3.6.5
    - VERSION=4.0.0

before_script: 
  - wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1404-$VERSION.tgz
  - tar xzvf mongodb-linux-x86_64-ubuntu1404-$VERSION.tgz
  - export PATH=$PWD/mongodb-linux-x86_64-ubuntu1404-$VERSION/bin:$PATH
  - mkdir $PWD/db
  - mongod --dbpath $PWD/db > /dev/null &

  - go build 
  - go get github.com/golang/lint/golint
  - golint ./... 

script:
  - ./test.sh
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: 
  email: false

git:
  depth: 3