language: go

go:
  - '1.10'

before_script: 
  - wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1404-3.6.3.tgz
  - tar xzvf mongodb-linux-x86_64-ubuntu1404-3.6.3.tgz
  - export PATH=$PWD/mongodb-linux-x86_64-ubuntu1404-3.6.3/bin:$PATH
  - mkdir $PWD/db
  - mongod --dbpath $PWD/db > /dev/null &

  - go build 
  - go get github.com/golang/lint/golint
  - golint ./... 

script:
  - ./test.sh
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: 
  email: false

git:
  depth: 3