language: go

dist: xenial

go:
  - 1.12.x

services:
  - mongodb

before_script: 
  - go build 
  - go get -u golang.org/x/lint/golint
  - golint ./... 

script:
  - scripts/test.sh
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: 
  email: false

git:
  depth: 3
