language: go

dist: xenial

go:
  - 1.11.x

env:
  matrix:
    - VERSION=4.0.4

before_script: 
  - wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-$VERSION.tgz
  - tar xzvf mongodb-linux-x86_64-ubuntu1604-$VERSION.tgz
  - export PATH=$PWD/mongodb-linux-x86_64-ubuntu1604-$VERSION/bin:$PATH
  - mkdir $PWD/db
  - mongod --dbpath $PWD/db > /dev/null &

  - go build 
  - go get -u golang.org/x/lint/golint
  - golint ./... 

script:
  - ./test.sh
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: 
  email: false

git:
  depth: 3
