version: '3'
services:
  mongodb:
    image: mongo
    network_mode: host
  web:
    build: . 
    depends_on: 
      - mongodb
    network_mode: host
    volumes:
      - ./storage:/app/storage
      - ./backups:/app/backups